name: CI
on: [push, pull_request]
permissions:
  id-token: write
  contents: write
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-node@v6
      with:
        node-version: latest
        cache: yarn
    - run: yarn
    - run: yarn test
    - if: github.ref == 'refs/heads/main'
      run: yarn release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
